#ifndef _FOREIGNCC_COMMON_COMMON_H_INCLUDED_
#define _FOREIGNCC_COMMON_COMMON_H_INCLUDED_

//
// Sanity check: Exactly one of BUILD_FOREIGNCC, BUILD_FOREIGNCCD, BUILD_FOREIGNCCCTL,
// BUILD_UNITTEST shall be defined true-like
//
#if !BUILD_FOREIGNCC && !BUILD_FOREIGNCCD && !BUILD_FOREIGNCCCTL && !BUILD_UNITTEST
#error "BUG: None of the following is defined true-like: BUILD_FOREIGNCC, BUILD_FOREIGNCCD, BUILD_FOREIGNCCCTL, BUILD_UNITTEST"
#elif (!!BUILD_FOREIGNCC + !!BUILD_FOREIGNCCD + !!BUILD_FOREIGNCCCTL + !!BUILD_UNITTEST > 1)
#error "BUG: More than one of the following is defined true-like: BUILD_FOREIGNCC, BUILD_FOREIGNCCD, BUILD_FOREIGNCCCTL, BUILD_UNITTEST"
#endif


#include <generated/config.h>


#endif // _FOREIGNCC_COMMON_COMMON_H_INCLUDED_
